all:
  hosts:
    node1:
      ansible_host: 192.168.3.191
      ip: 192.168.3.191
      access_ip: 192.168.3.191
    node2:
      ansible_host: 192.168.3.192
      ip: 192.168.3.192
      access_ip: 192.168.3.192
    node3:
      ansible_host: 192.168.3.193
      ip: 192.168.3.193
      access_ip: 192.168.3.193
    node4:
      ansible_host: 192.168.3.194
      ip: 192.168.3.194
      access_ip: 192.168.3.194
    node5:
      ansible_host: 192.168.3.195
      ip: 192.168.3.195
      access_ip: 192.168.3.195
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
