# Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer

# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: frontend

# replicas and update
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

#  strategy:
#    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:php8.0-apache
        name: wordpress
# set root pass from secret  
        env:
        - name: WORDPRESS_DB_HOST
          value: wordpress-mysql # from service name mysql
        
        - name: WORDPRESS_DB_NAME
          value: WEB

        - name: WORDPRESS_DB_USER
          value: admin
        
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password 

        ports:
        - containerPort: 80
          name: wordpress
# Mount Volume for Pod          
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html

# Volume from PVC
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim


# PVC
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: longhorn  # storageclass
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi